# SPDX-License-Identifier: GPL-2.0
# K1 Platform Support
snd-soc-k1-i2s-y := k1_i2s.o

obj-$(CONFIG_SND_SOC_K1_I2S) += snd-soc-k1-i2s.o

# K3 Platform Support
snd-soc-k3-ri2s-y := k3_ri2s.o

obj-$(CONFIG_SND_SOC_K3_RI2S) += snd-soc-k3-ri2s.o

# K1 HDMI audio
snd-soc-k1-hdmi-audio-y := k1_hdmi_audio.o

obj-$(CONFIG_SND_SOC_K1_HDMI_AUDIO) += snd-soc-k1-hdmi-audio.o
